"""add column view to tabel message

Revision ID: a889501940a0
Revises: 5270f53d6d10
Create Date: 2018-09-13 22:51:40.943002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a889501940a0'
down_revision = '5270f53d6d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'view')
    # ### end Alembic commands ###
